alpha_blog/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :chapters
  resources :materials do 
    resources :chapters
  end
  root 'pages#home'
  get 'about', to: 'pages#about'
end

alpha_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

alpha_blog/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

alpha_blog/app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :material
  validates :chapter_num, presence: true
  validates :title, presence: true
  validates :page_start_at, presence: true
end

alpha_blog/app/models/material.rb
class Material < ApplicationRecord
  has_many :chapters
  validates :material_id, presence: true, uniqueness: true, length: { minimum: 3, maximum: 5 }
end

alpha_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: 'Hello World!'
  end
end

alpha_blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

alpha_blog/app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]
  
  def index
    @chapters = Chapter.all
  end
  
  def show
  end
  
  def new
    @chapter = Chapter.new
  end
  
  def edit
  end
  
  def create
    @chapter = Chapter.new(chapter_params)
    @chapter.material = Material.first
    if @chapter.save
      flash[:notice] = 'Chapter was created successfully.'
      redirect_to @chapter
    else
      render 'new'
    end
  end
  
  def update
    if @chapter.update(chapter_params)
      flash[:notice] = 'Chapter was updated successfully.'
      redirect_to @chapter
    else
      render 'edit'
    end
  end
  
  def destroy
    @chapter.destroy
    redirect_to chapters_path
  end
  
  private
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end
    
    def chapter_params
      params.require(:chapter).permit(:chapter_num, :title, :page_start_at)
    end
end

alpha_blog/app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show]
  
  def index
    @materials = Material.all
  end
  
  def show
  end
  
  private
    def set_material
      @material = Material.find(params[:id])
    end
end

alpha_blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

alpha_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

alpha_blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

alpha_blog/app/helpers/pages_helper.rb
module PagesHelper
end

alpha_blog/app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

alpha_blog/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

alpha_blog/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

alpha_blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

alpha_blog/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

alpha_blog/app/views/chapters/_form.html.erb
<%= render 'shared/errors' %>
<%= form_with(model: @chapter, local: true) do |f| %>
  <div class="input-group">
    <p><%= f.text_field :chapter_num, placeholder: 'Chapter number', class: "form-control" %></p>
    <p><%= f.text_field :title, placeholder: 'Chapter title', class: "form-control" %></p>
    <p><%= f.text_field :page_start_at, placeholder: 'Chapter starts at', class: "form-control" %></p>
    <p><%= f.submit class: "btn btn-outline-success btn-md" %></p>
  </div>
<% end %>

<%= link_to 'Cancel and return to chapters listing', chapters_path, class: "btn btn-warning text-light btn-sm" %>

alpha_blog/app/views/chapters/edit.html.erb
<h1>Edit chapter</h1>

<%= render 'form' %>

alpha_blog/app/views/chapters/index.html.erb
<h1 class="text-center mt-4">Listing all chapters</h1>

<div class="container">
  <% @chapters.each do |chapter| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            Material <%= chapter.material.slides_filename if chapter.material %>
          </div>
          <div class="card-body">
            <p class="card-text">Chapter <%= chapter.chapter_num %></p>
            <h5 class="card-title"><%= link_to chapter.title, chapter_path(chapter), class: "text-success" %></h5>
            <p class="card-text">Slide <%= chapter.page_start_at %></p>
            <%= link_to 'View', chapter_path(chapter), class: "btn btn-outline-success" %>
            <%= link_to 'Edit', edit_chapter_path(chapter), class: "btn btn-outline-info" %>
            <%= link_to 'Delete', chapter_path(chapter), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %></a>
          </div>
          <div class="card-footer text-muted">
            <small>Created at <%= time_ago_in_words(chapter.created_at) %> ago,
            edited <%= time_ago_in_words(chapter.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<p><%= link_to 'Create new chapter', new_chapter_path %></p>

alpha_blog/app/views/chapters/new.html.erb
<h1>Create a new chapter</h1>

<%= render 'form' %>

alpha_blog/app/views/chapters/show.html.erb
<h1><%= @chapter.material.slides_filename if @chapter.material %></h1>

<p>
  <strong>Chapter Number:</strong>
  <%= @chapter.chapter_num %>
</p>
<p>
  <strong>Title:</strong>
  <%= @chapter.title %>
</p>
<p>
  <strong>Starts at:</strong>
  <%= @chapter.page_start_at %>
</p>

<%= link_to 'Edit', edit_chapter_path(@chapter), class: "btn btn-outline-info" %>
<%= link_to 'Delete', chapter_path(@chapter), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>

alpha_blog/app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light">
  <div class="container text-center">
    <span class="text-muted">Copyright &copy; 2021 Cindy Le</span>
  </div>
</footer>

alpha_blog/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-success" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

alpha_blog/app/views/layouts/_navigation.html.erb
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">

        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>

          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>

          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <img class="block lg:hidden h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
          <img class="hidden lg:block h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-500-mark-white-text.svg" alt="Workflow">
        </div>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <%= link_to "Home", root_path, class: "bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium", id: "logo" %>
            <%= link_to "Articles", articles_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "Chapters", chapters_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "Materials", materials_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          </div>
        </div>
      </div>

    </div>
  </div>


  <div class="sm:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1">

      <a href="#" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium">Dashboard</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Team</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Projects</a>
    </div>
  </div>
</nav>

alpha_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100 bg-gray-100">
    <%= render 'layouts/navigation' %>
    <main class="flex-shrink-0">
      <div class="container">
        <div class="bg-light p-5 rounded">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

alpha_blog/app/views/materials/index.html.erb
<%= @materials %>

alpha_blog/app/views/materials/show.html.erb
Number of chapters <%= @material.chapters.size %><br>
All Chapters for <%= @material.material_id %>: <%= @material.slides_filename %><br>

<% for chapter in @material.chapters %>
  <%= chapter.chapter_num %> | <%= chapter.title %> | <%= chapter.page_start_at %>
  <br>
<% end %>

alpha_blog/app/views/pages/about.html.erb
<h1>This is the About page</h1>

<%= link_to 'Chapters listing', chapters_path %> |
<%= link_to 'Home page', root_path %>

alpha_blog/app/views/pages/home.html.erb
<h1>This is the Home page</h1>

<%= link_to 'Chapters listing', chapters_path %> |
<%= link_to 'About page', about_path %>

alpha_blog/app/views/shared/_errors.html.erb
<% if @chapter.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The follow error(s) prevented the chapter from being saved:</h4>
    <hr>
    <ul>
      <% @chapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>